# Generated by Django 3.2.2 on 2021-05-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_location_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='main_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='main_temp_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='main_temp_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='weather_desc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='weather_icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='weather_main',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
